// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1SoQASRxX2cWFv5k5AJGUExkoKZT0dM',
    appId: '1:1075917118681:web:f44f42656938cf1c72b2c8',
    messagingSenderId: '1075917118681',
    projectId: 'sempro-805d4',
    authDomain: 'sempro-805d4.firebaseapp.com',
    storageBucket: 'sempro-805d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS2_73LSBIEmiuhSR3kNseWBBWuSeAva4',
    appId: '1:1075917118681:android:e0687a437717cb8b72b2c8',
    messagingSenderId: '1075917118681',
    projectId: 'sempro-805d4',
    storageBucket: 'sempro-805d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1BXodc8jUWZv7vyIr3mMOf0OCBbZdnE',
    appId: '1:1075917118681:ios:10b7c9e705a504e872b2c8',
    messagingSenderId: '1075917118681',
    projectId: 'sempro-805d4',
    storageBucket: 'sempro-805d4.appspot.com',
    iosBundleId: 'com.example.flutterProject1',
  );
}
